[package]
name = "zed_snippets"
version = "0.0.5"
edition.workspace = true
publish.workspace = true
license = "Apache-2.0"

[lints]
workspace = true

[lib]
path = "src/snippets.rs"
crate-type = ["cdylib"]

[dependencies]
serde_json = "1.0"
zed_extension_api = "0.1.0"
